# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cD_uxR9kgGSFSBiXkbnirAVPGMjz7KxZ
"""

# !pip install prince  # Instala la librería prince (para análisis FAMD)

import pandas as pd  # Importa pandas para manejo de datos
import numpy as np  # Importa numpy para operaciones numéricas
import matplotlib.pyplot as plt  # Importa matplotlib para gráficos básicos
import seaborn as sns  # Importa seaborn para gráficos estadísticos
import prince  # Importa prince para análisis FAMD
from sklearn.cluster import KMeans # Importa KMeans para clustering
from sklearn.metrics import silhouette_score, davies_bouldin_score  # Importa métricas de evaluación

# CARGA DE DATOS
datos = pd.read_excel("Bird migration dataset.xls")  # Carga el archivo Excel en un DataFrame

# LIMPIEZA DE COLUMNAS
datos.columns = (  # Modifica los nombres de las columnas
    datos.columns  # Toma las columnas originales
    .str.strip()  # Elimina espacios al inicio y final
    .str.lower()   # Convierte todo a minúsculas
    .str.replace(" ", "_")  # Reemplaza espacios por guiones bajos
    .str.replace(r"[^\w]", "", regex=True)  # Elimina caracteres especiales
)

print(datos.columns)                 # Imprime los nombres de las columnas ya limpias

#  RENOMBRAR COLUMNAS
datos = datos.rename(columns={  # Renombra columnas específicas
    "gps_yy": "lat",  # Cambia gps_yy a lat
    "gps_xx": "lon",  # Cambia gps_xx a lon
    "migration_start_month": "inicio_mes",  # Cambia nombre a inicio_mes
    "migration_end_month": "fin_mes",  # Cambia nombre a fin_mes
    "migration_start_year": "inicio_año",  # Cambia nombre a inicio_año
    "migration_end_year": "fin_año",  # Cambia nombre a fin_año
    "migration_nodes": "nodo",  # Cambia nombre a nodo
    "migratory_route_codes": "ruta_codigo",  # Cambia nombre a ruta_codigo
})

#  LIMPIEZA DE COORDENADAS
datos["lat"] = datos["lat"].astype(str)  # Convierte latitud a string
datos["lat"] = datos["lat"].str.replace(",", ".")  # Reemplaza coma por punto
datos["lat"] = datos["lat"].astype(float)  # Convierte a número float

datos["lon"] = datos["lon"].astype(str)  # Convierte longitud a string
datos["lon"] = datos["lon"].str.replace(",", ".")  # Reemplaza coma por punto
datos["lon"] = datos["lon"].astype(float)  # Convierte a float

#  CONVERSIÓN NUMÉRICA
datos["inicio_mes"] = pd.to_numeric(datos["inicio_mes"], errors="coerce")  # Convierte a número
datos["fin_mes"] = pd.to_numeric(datos["fin_mes"], errors="coerce")  # Convierte a número
datos["inicio_año"] = pd.to_numeric(datos["inicio_año"], errors="coerce")  # Convierte a número
datos["fin_año"] = pd.to_numeric(datos["fin_año"], errors="coerce") # Convierte a número

# ELIMINAR NULOS
datos = datos.dropna(subset=["lat", "lon"])  # Elimina filas sin coordenadas

#  CREACIÓN DE FECHAS
datos["fecha_inicio"] = pd.to_datetime(  # Crea fecha de inicio
    dict(year=datos["inicio_año"], month=datos["inicio_mes"], day=1)  # Usa día fijo = 1
)

datos["fecha_fin"] = pd.to_datetime(  # Crea fecha de fin
    dict(year=datos["fin_año"], month=datos["fin_mes"], day=1)  # Usa día fijo = 1
)

#  DURACIÓN
datos["duracion_migracion"] = (  # Calcula duración en meses
    (datos["fecha_fin"].dt.year - datos["fecha_inicio"].dt.year) * 12 +  # Diferencia en años * 12
    (datos["fecha_fin"].dt.month - datos["fecha_inicio"].dt.month  # Suma diferencia en meses
)

print(datos.info())  # Muestra información del dataset

#  GRÁFICO DISPERSIÓN
plt.figure()  # Crea figura
scatter = plt.scatter(datos["lon"], datos["lat"], c=datos["inicio_mes"])  # Grafico scatter
plt.title("Distribución espacial según mes de inicio")  # Título
plt.xlabel("Longitud")  # Etiqueta eje X
plt.ylabel("Latitud")  # Etiqueta eje Y
plt.colorbar(scatter)  # Barra de color
plt.show() # Muestra gráfico

#  MAPEO DE VARIABLES
datos["continente"] = datos["continente"].map({  # Convierte códigos a nombres
    1: "North America",
    2: "South America",
    3: "Europe",
    4: "Africa",
    5: "Asia",
    6: "Oceania"
})

datos["inter_intra_continente"] = datos["inter_intra_continente"].map({  # Tipo migración
    1: "Intercontinental",
    2: "Intracontinental"
})

#  FUNCIÓN DE ETIQUETAS
def poner_valores(ax, total):  # Define función para mostrar porcentajes
    for p in ax.patches: # Recorre cada barra
        altura = p.get_height()  # Obtiene altura
        if altura > 0:  # Verifica valor válido
            porcentaje = 100 * altura / total  # Calcula porcentaje
            ax.annotate(f'{porcentaje:.3f}%',  # Texto a mostrar
                        (p.get_x() + p.get_width() / 2., altura + 0.5),  # Posición
                        ha='center', va='bottom')  # Alineación

#  CLUSTERING
datos_famd = datos.copy()  # Copia de datos

numericas = ["lat", "lon", "duracion_migracion"]  # Variables numéricas
categoricas = ["bird_species", "ruta", "inter_intra_continente"]  # Variables categóricas

datos_famd = datos_famd[numericas + categoricas].dropna()  # Elimina nulos

for col in categoricas:   # Recorre columnas categóricas
    datos_famd[col] = datos_famd[col].astype(str)  # Convierte a string

datos_famd[numericas] = datos_famd[numericas].apply(pd.to_numeric)  # Convierte a numérico

famd = prince.FAMD(n_components=6, random_state=42)  # Crea modelo FAMD
famd = famd.fit(datos_famd)            # Ajusta modelo

datos_famd_trans = famd.transform(datos_famd)  # Transforma datos

#  KMEANS
X_cluster = datos_famd_trans.iloc[:, :5]  # Selecciona dimensiones

kmeans = KMeans(n_clusters=2, random_state=42)  # Crea modelo
clusters = kmeans.fit_predict(X_cluster)        # Entrena modelo

datos_famd["cluster"] = clusters               # Guarda clusters

#  MÉTRICAS
sil = silhouette_score(X_cluster, clusters)  # Calcula silhouette
db = davies_bouldin_score(X_cluster, clusters)  # Calcula DB index

print("Silhouette:", sil)  # Imprime resultado
print("Davies-Bouldin:", db)  # Imprime resultado

class AnalisisMigracion:

    def __init__(self, ruta_archivo):
        self.ruta = ruta_archivo
        self.datos = None

    def cargar_datos(self):
        self.datos = pd.read_excel(self.ruta)

    def limpiar_datos(self):
        # aquí va toda tu limpieza
        pass

    def analizar(self):
        # aquí FAMD + clustering
        pass

    def graficar(self):
        # aquí tus gráficos
        pass


# EJECUCIÓN
if __name__ == "__main__":
    analisis = AnalisisMigracion("Bird migration dataset.xls")
    analisis.cargar_datos()
    analisis.limpiar_datos()
    analisis.analizar()
    analisis.graficar()